### ISSUE TITLE
The using sisl/AutomotiveDrivingModels.jl doesn't contain type IntegratedContinuous' definition

### ISSUE THREAD

**Issue by gdpinchina** [sisl/latent_driver#1]
Type `IntegratedContinuous` has been used in several files in `sisl/lantent_driver`. Such as:
`sisl/latentdriver/pull_traces/passive_aggressive.jl    row:89
sisl/latentdriver/pull_traces/pull_2d_traces_passive_aggressive.jl    row:59
sisl/latentdriver/validation/AutoViz.jl    row25
...`
I can't find this type's definition in `sisl/AutomotiveDrivingModels.jl`. But I can find the definition in `maxiaoba/LofiSimu/AutomotiveDrivingModels.jl`. I have searched the whole github with the key word: `IntegratedContinuous` and I found that only the latter contains a definition to `IntegratedContinuous`. And the latter seem raise much less concern in github. Now that these two repositories are in a same organization, why the  `sisl/AutomotiveDrivingModels.jl` cannot support `sisl/lantent_driver`.
Thank you for your time.

**Comment by tawheeler** [comment]
@Jgmorton maybe the Readme should point to a version of each package dependency at the time of release.

**Comment by Jgmorton** [comment]
Yes unfortunately it requires an old version of AutomotiveDrivingModels.  I updated the readme to link to an old commit.

**Comment by gdpinchina** [comment]
Thanks a lot for your help, I'm closing the issue.
